amqp:
  hostname: amqp://localhost
  port: 5672
api:
  hostname: localhost
  port: 8080
host:
  hostname: localhost
  port: 9099
socket:
  listener:
    hostname: localhost
    port: 20001
  sender:
    hostname: localhost
    port: 20002
cluster:
  name: "CLUSTER1"
  node: "NODE1"
  namespace: "Default"
statusresource:
pubfilepath: pub.json
subfilepath: pub.json
publishstatus: false
protocol: SOCKET #SOCKET HTTP
apipathprefix: "/api/ocloudnotifications/v1"
hostapipathprefix: "/api/"