---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ptp-config
  namespace: default
data:
  config.yml: |-
    amqp:
      hostname: amqp://amqp-dispatch-service
      port: 5672
    api:
      hostname: localhost
      port: 8080
    host:
      hostname: localhost
      port: 9090
    socket:
      listener:
        hostname: localhost
        port: 20001
      sender:
        hostname: ""
        port: 20002
    cluster:
      name: ""
      node: ""
      namespace: ""
    statusresource:
    - name: ptp-status
    pubfilepath: /store/pub.json
    subfilepath: /store/sub.json
    publishstatus: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vdu-config
  namespace: default
data:
  config.yml: |-
    amqp:
      hostname: amqp://amqp-dispatch-service
      port: 5672
    api:
      hostname: localhost
      port: 8080
    host:
      hostname: localhost
      port: 9090
    socket:
      listener:
        hostname: localhost
        port: 20001
      sender:
        hostname: localhost
        port: 20002
    cluster:
      name: ""
      node: ""
      namespace: ""
    statusresource:
    pubfilepath: /store/pub.json
    subfilepath: /store/sub.json
    publishstatus: false
