apiVersion: apps/v1
kind: Deployment
metadata:
  name: vdu-deployment-remote
  labels:
    app: vdu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vdu
  template:
    metadata:
      labels:
        app: vdu
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: local-app
                    operator: In
                    values:
                      - remote
      containers:
        - name: vdu
          image: vdu
          command: [ "./vdu" ]
          args: [ "-config", "/opt/config.yml" ]
          livenessProbe:
            httpGet:
              path: /api/vdu/v1/health
              port: 9090
            initialDelaySeconds: 3
            periodSeconds: 3
          env:
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          volumeMounts:
            - name: config-volume
              mountPath: /opt/
            - name: pubsubs
              mountPath: /store
        - name: vdu-sidecar
          image: sidecar
          command: [ "./sidecar" ]
          args: [ "-config", "/opt/config.yml" ]
          livenessProbe:
            httpGet:
              path: /api/ocloudnotifications/v1/health
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3
          env:
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          volumeMounts:
            - name: config-volume
              mountPath: /opt/
            - name: pubsubs
              mountPath: /store
      volumes:
        - name: config-volume
          configMap:
            name: vdu-config-remote
            items:
              - key: config.yml
                path: config.yml
        - name: pubsubs
          emptyDir: {}



