apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-events-consumer-deployment
  labels:
    app: cloudevents-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudevents-consumer
  template:
    metadata:
      labels:
        app: cloudevents-consumer
    spec:
      containers:
        - name: cloudevents-consumer
          image: consumer
          env:
            - name: AMQP_URL
              value: "amqp://amqp-dispatch-service:5672/test2"