apiVersion: apps/v1
kind: Deployment
metadata:
  name: vdu-deployment
  labels:
    app: vdu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vdu
  template:
    metadata:
      labels:
        app: vdu
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: local-app
                    operator: In
                    values:
                      - local
      containers:
        - name: vdu
          image: vdu
          env:
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
        - name: vdu-sidecar
          image: sidecar
          lifecycle:
            type: Sidecar
          command: [ "./sidecar" ]
          args: [ "-config", "/opt/config.yml" ]
          volumeMounts:
            - name: config-volume
              mountPath: /opt/
            - name: pubsubs
              mountPath: /store
      volumes:
        - name: config-volume
          configMap:
            name: vdu-config
            items:
              - key: config.yml
                path: config.yml
        - name: pubsubs
          emptyDir: { }



