apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ptp-deployment
  labels:
    app: ptp-daemon
spec:
  #replicas: 1
  selector:
    matchLabels:
      app: ptp-daemon
  template:
    metadata:
      labels:
        app: ptp-daemon
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: local-app
                    operator: In
                    values:
                      - local
      containers:
        - name: ptp-daemon
          image: ptp
          command: [ "./ptp" ]
          args: [ "-config", "/opt/config.yml" ]
          env:
            - name: MSG_PER_SEC
              value: "100"
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          volumeMounts:
            - name: config-volume
              mountPath: /opt/
            - name: pubsubs
              mountPath: /store
            - name: socket-dir
              mountPath: /tmp
        - name: ptp-sidecar
          image: sidecar
          command: [ "./sidecar" ]
          args: [ "-config", "/opt/config.yml" ]
          env:
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          volumeMounts:
            - name: config-volume
              mountPath: /opt/
            - name: pubsubs
              mountPath: /store
            - name: socket-dir
              mountPath: /tmp
      volumes:
        - name: config-volume
          configMap:
            name: ptp-config
            items:
              - key: config.yml
                path: config.yml
        - name: pubsubs
          emptyDir: {}
        - name: socket-dir
          emptyDir: {}



