apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ptp-deployment
  labels:
    app: ptp-daemon
spec:
  #replicas: 1
  selector:
    matchLabels:
      app: ptp-daemon
  template:
    metadata:
      labels:
        app: ptp-daemon
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: local-app
                    operator: In
                    values:
                      - local
      containers:
        - name: ptp-daemon
          securityContext:
            privileged: true
          image: ptp
          command: [ "./ptp" ]
          args: [ "-config", "/opt/config.yml" ]
          ports:
            - containerPort: 9090
          livenessProbe:
            httpGet:
              path: /api/ptp/v1/health
              port: 9090
            initialDelaySeconds: 5
            periodSeconds: 3
          env:
            - name: MSG_PER_SEC
              value: "100"
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: ENABLE_EVENT
              value: "True"
          volumeMounts:
            - name: config-volume
              mountPath: /opt/
            - name: pubsubs
              mountPath: /store
            - name: socket-dir
              mountPath: /var/run
        - name: ptp-sidecar
          securityContext:
            privileged: true
          image: ptpsidecar
          command: [ "./ptpsidecar" ]
          args: [ "-config", "/opt/config.yml" ]
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /api/ocloudnotifications/v1/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 3
          env:
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          volumeMounts:
            - name: config-volume
              mountPath: /opt/
            - name: pubsubs
              mountPath: /store
            - name: socket-dir
              mountPath: /var/run
      volumes:
        - name: config-volume
          configMap:
            name: ptp-config
            items:
              - key: config.yml
                path: config.yml
        - name: pubsubs
          emptyDir: {}
        - hostPath:
            path: /var/run/ptp
            type: DirectoryOrCreate
          name: socket-dir




