apiVersion: v1
kind: Service
metadata:
  name: ptp-service
  labels:
    app: ptp-daemon
spec:
  ports:
    - port: 20001
      name: udp
    - port: 20002
      name: udp
  selector:
    app: ptp-daemon
---
apiVersion: v1
kind: Service
metadata:
  name: vdu-service
  labels:
    app: vdu
spec:
  ports:
    - port: 30001
      name: udp
    - port: 30002
      name: udp
  selector:
    app: vdu