apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- 000-config.yml
- 03-vdu.yaml
- 04-ptp.yaml
- 006-vdu-remote.yml
replicas:
- count: 1
  name: vdu-deployment
#- count: 1
#  name: ptp-deployment
images:
- name: ptp
  newName: quay.io/aneeshkp/ptp
  newTag: "4.8"
- name: ptpsidecar
  newName: quay.io/aneeshkp/ptpsidecar
  newTag: "4.8"
- name: sidecar
  newName: quay.io/aneeshkp/sidecar
  newTag: "4.8"
- name: vdu
  newName: quay.io/aneeshkp/vdu
  newTag: "4.8"
