apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
#- 02-producer.yaml
resources:
- 003-service.yaml
- 000-amqpconfig.yml
- 00-qpid-dispatcher.yaml
- 01-consumer.yaml
- 004-cnf.yaml
- 005-yolo-service.yaml
#- name: producer
#  newName: quay.io/aneeshkp/cloudevents-sender
#  newTag: latest
replicas:
  - name: cloud-events-consumer-deployment
    count: 16
images:
- name: cnf
  newName: quay.io/aneeshkp/cnf-yolo
  newTag: latest
- name: consumer
  newName: quay.io/aneeshkp/cloudevents-receiver
  newTag: latest
- name: producer
  newName: quay.io/aneeshkp/cloudevents-sender
  newTag: latest
- name: sidecar
  newName: quay.io/aneeshkp/sidecar-yolo
  newTag: latest
