apiVersion: apps/v1
kind: Deployment
metadata:
  name: qpid-dispatcher-deployment-a
  labels:
    app: qpid-dispatcher-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qpid-dispatcher-a
  template:
    metadata:
      labels:
        app: qpid-dispatcher-a
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: local-app
                    operator: In
                    values:
                      - yolo
      containers:
        - name: qpid-dispatcher-a
          image: quay.io/interconnectedcloud/qdrouterd:1.14.0
          resources:
            requests:
              cpu: "50m"
            limits:
              cpu: "50m"
          volumeMounts:
            - name: qpidrouter-config-a
              mountPath: /etc/qpid-dispatch/
      volumes:
          - name: qpidrouter-config-a
            configMap:
              name: qpidrouter-config-a
              items:
                - key: qdrouterd.conf
                  path: qdrouterd.conf
