apiVersion: v1
kind: Service
metadata:
  name: amqp-dispatch-service-a
  labels:
    app: qpid-dispatcher-a
spec:
  ports:
    - port: 5672
      name: amqp
  selector:
    app: qpid-dispatcher-a
---
apiVersion: v1
kind: Service
metadata:
  name: amqp-dispatch-service-b
  labels:
    app: qpid-dispatcher-b
spec:
  ports:
    - port: 5672
      name: amqp
  selector:
    app: qpid-dispatcher-b

---
apiVersion: v1
kind: Service
metadata:
  name: amqp-dispatch-listener-service-b
  labels:
    app: qpid-dispatcher-b
spec:
  ports:
    - port: 20001
      name: tcp
  selector:
    app: qpid-dispatcher-b