apiVersion: v1
kind: Service
metadata:
  name: amqp-dispatch-service-a
  labels:
    app: qpid-dispatcher-a
spec:
  ports:
    - port: 5672
      name: amqp
  selector:
    app: qpid-dispatcher-a
---
apiVersion: v1
kind: Service
metadata:
  name: amqp-dispatch-service-b
  labels:
    app: qpid-dispatcher-b
spec:
  ports:
    - port: 5672
      name: amqp
  selector:
    app: qpid-dispatcher-b
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: amqp-dispatch-service-c
#  labels:
#    app: qpid-dispatcher-c
#spec:
#  ports:
#    - port: 5672
#      name: amqp
#  selector:
#    app: qpid-dispatcher-c
---
apiVersion: v1
kind: Service
metadata:
  name: amqp-dispatch-router-service-a
  labels:
    app: qpid-dispatcher-a
spec:
  type: NodePort
  ports:
    - port: 20001
      targetPort: 20001
      nodePort: 30036
  selector:
    app: qpid-dispatcher-a
---
apiVersion: v1
kind: Service
metadata:
  name: amqp-dispatch-router-service-b
  labels:
    app: qpid-dispatcher-b
spec:
  type: NodePort
  ports:
    - port: 20001
      targetPort: 20001
      nodePort: 30037
  selector:
    app: qpid-dispatcher-b
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: amqp-dispatch-router-service-c
#  labels:
#    app: qpid-dispatcher-c
#spec:
#  type: NodePort
#  ports:
#    - port: 20002
#      targetPort: 20001
#      nodePort: 30038
#  selector:
#    app: qpid-dispatcher-c