apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- 000-config.yml
- 00-qpid-dispatcher.yaml
- 003-service.yaml
replicas:
  - name: qpid-dispatcher-deployment-a
    count: 1
  - name: qpid-dispatcher-deployment-b
    count: 1
#  - name: qpid-dispatcher-deployment-c
#    count: 1