amqp:
  hostname: amqp://localhost
  port: 5672
api:
  hostname: localhost
  port: 8080
host:
  hostname: localhost
  port: 9090
socket:
  listener:
    hostname: localhost
    port: 20001
  sender:
    hostname: localhost
    port: 20002
cluster:
  name: "CLUSTER1"
  node: "NODE1"
  namespace: "Default"
statusResource:
  name: []
  status:
    publishStatus: true
    enableStatusCheck: false
eventHandler: "HTTP"
apiPathPrefix: "/api/ocloudnotifications/v1"
hostPathPrefix: "/api/ptp/v1"
store:
  pubFilePath: "pub.json"
  subFilePath: "sub.json"